// Product catalog. Prices are in USD.

// Section order for the storefront. Each product below has a `category`
// matching one of these keys.
const CATEGORIES = [
  { id: "apparel", label: "Apparel" },
  { id: "accessories", label: "Accessories" },
  { id: "race-car-parts", label: "Race Car Parts" },
  { id: "3d-art", label: "3D Art" },
];

const PRODUCTS = [
  {
    id: "tshirt-womens-pink",
    category: "apparel",
    name: "Women in Motorsports Pink T-Shirt",
    images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"],
    description: "100% cotton short sleeve t-shirt with a Frog Racing logo on the front and the Women in Motorsports logo on the back. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    variants: [
      { id: "s", label: "S", price: 25.00, images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"] },
      { id: "m", label: "M", price: 25.00, images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"] },
      { id: "l", label: "L", price: 25.00, images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"] },
      { id: "xl", label: "XL", price: 25.00, images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"] },
      { id: "2xl", label: "2XL", price: 25.00, images: ["images/tshirt-womens-pink/front.jpg", "images/tshirt-womens-pink/back.jpg"] },
    ],
    shipping: { first: 7.00, additional: 2.00 },
  },
  {
    id: "tshirt-womens-black-longsleeve",
    category: "apparel",
    name: "Women in Motorsports Black T-Shirt Long Sleeves",
    images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"],
    description: "100% cotton long sleeve t-shirt with a Frog Racing logo on the front and the Women in Motorsports logo on the back. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    variants: [
      { id: "s", label: "S", price: 35.00, images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"] },
      { id: "m", label: "M", price: 35.00, images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"] },
      { id: "l", label: "L", price: 35.00, images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"] },
      { id: "xl", label: "XL", price: 35.00, images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"] },
      { id: "2xl", label: "2XL", price: 35.00, images: ["images/tshirt-womens-black-longsleeve/front.png", "images/tshirt-womens-black-longsleeve/back.png"] },
    ],
    shipping: { first: 7.00, additional: 2.00 },
  },
  {
    id: "hat",
    category: "apparel",
    name: "Frog Racing Embroidered Hat",
    images: ["images/hat/front.jpg", "images/hat/back.jpg"],
    description: "100% cotton unisex hat with an embroidered Frog Racing logo and a rear clasp for adjustment. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 35.00,
    shipping: { first: 6.00, additional: 1.00 },
  },
  {
    id: "key-ring",
    category: "accessories",
    name: "Women in Motorsports Key Ring",
    images: ["images/key-ring/cttc-2026.jpg", "images/key-ring/both.jpg"],
    description: "Laser engraved transparent acrylic key ring with a lobster claw clasp made of zinc alloy metal, featuring the Frog Racing and Women in Motorsports logo. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    variants: [
      { id: "cttc-2026", label: "CTTC 2026", price: 3.00, images: ["images/key-ring/cttc-2026.jpg", "images/key-ring/both.jpg"] },
      { id: "frog-racing", label: "Frog Racing", price: 3.00, images: ["images/key-ring/frog-racing.jpg", "images/key-ring/both.jpg"] },
    ],
    shipping: { first: 2.00, additional: 0.50 },
  },
  {
    id: "license-plate-cover",
    category: "accessories",
    name: "Frog Racing License Plate Cover",
    image: "images/license-plate-cover/front.jpg",
    description: "3D printed in-house by Frog Racing from PETG filament. Features a translucent green Frog Racing in a black frame. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 10.00,
    shipping: { first: 6.00, additional: 1.00 },
  },
  {
    id: "wim-sticker",
    category: "accessories",
    name: "Women in Motorsport Sticker",
    image: "images/wim-sticker/front.jpg",
    description: "Our Women in Motorsport sticker from our all women team at CTTC 2026. A piece of history for the first ever women team at this event, also setting a new all time record for fastest woman! Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 5.00,
    shipping: { first: 1.00, additional: 0.00 },
  },
  {
    id: "frog-racing-sticker",
    category: "accessories",
    name: "Frog Racing Sticker",
    image: "images/frog-racing-sticker/front.jpg",
    description: "Our legendary Frog Racing logo in a cutout sticker! Size is approximately 2x2\". A great add-on to any order! Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 2.00,
    shipping: { first: 1.00, additional: 0.00 },
  },
  {
    id: "hood-pin-clips",
    category: "race-car-parts",
    pageUrl: "https://www.frogracing.us/store/hood-pin-clips",
    name: "Frog Racing Hood Pin Clips",
    images: ["images/hood-pin-clips/4clips.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
    description: "The Frog Racing hood pin clips secure your hood pins in place (made for hood pins with 6mm diameter pins and 3mm rings). It is made of ASA filament and 3D printed in house by Frog Racing. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    variants: [
      {
        id: "clips-only",
        label: "4 clips only",
        price: 2.00,
        // Free as an additional item alongside any other hood pin clips option
        // (still pays the normal $5.50 first-item rate if ordered alone).
        shippingAdditional: 0,
        images: ["images/hood-pin-clips/4clips.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
      {
        id: "holder-2",
        label: "4 clip + key ring clip holder (holds 2 clips)",
        price: 10.00,
        images: ["images/hood-pin-clips/holder2.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
      {
        id: "holder-4",
        label: "4 clip + key ring clip holder (holds 4 clips)",
        price: 10.00,
        images: ["images/hood-pin-clips/holder4.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
      {
        id: "signs",
        label: "4 clips + 2 service in progress clip-on signs",
        price: 10.00,
        images: ["images/hood-pin-clips/front.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
      {
        id: "combo-2",
        label: "Full combo (2 clips capacity key ring)",
        price: 15.00,
        images: ["images/hood-pin-clips/combo2.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
      {
        id: "combo-4",
        label: "Full combo (4 clips capacity key ring)",
        price: 15.00,
        images: ["images/hood-pin-clips/combo4.jpg", "images/hood-pin-clips/2.jpg", "images/hood-pin-clips/3.jpg", "images/hood-pin-clips/pin-size.jpg", "images/hood-pin-clips/ring-size.jpg"],
      },
    ],
    shipping: { first: 5.50, additional: 1.00 },
  },
  {
    id: "racing-harness-collar",
    category: "race-car-parts",
    name: "Racing Harness Collar",
    pageUrl: "https://www.frogracing.us/store/racing-harness-collars",
    image: "images/racing-harness-collar/38mm-2in.jpg",
    description: "Carbon Fiber reinforced polyamide (PA6-CF) racing harness collar with carbon steel hardware, designed and produced in-house at Frog Racing.",
    variants: [
      { id: "38mm-2in", label: "1.5\" / 38mm harness bar - 2\" belt kit", price: 44.99, image: "images/racing-harness-collar/38mm-2in.jpg" },
      { id: "38mm-3in", label: "1.5\" / 38mm harness bar - 3\" belt kit", price: 44.99, image: "images/racing-harness-collar/38mm-3in.jpg" },
      { id: "44mm-2in", label: "1.75\" / 44mm harness bar - 2\" belt kit", price: 49.99, image: "images/racing-harness-collar/44mm-2in.jpg" },
      { id: "44mm-3in", label: "1.75\" / 44mm harness bar - 3\" belt kit", price: 49.99, image: "images/racing-harness-collar/44mm-3in.jpg" },
      { id: "fia40mm-2in", label: "FIA 40mm harness bar - 2\" belt kit", price: 47.99, image: "images/racing-harness-collar/fia40mm-2in.jpg" },
      { id: "fia40mm-3in", label: "FIA 40mm harness bar - 3\" belt kit", price: 47.99, image: "images/racing-harness-collar/fia40mm-3in.jpg" },
    ],
    // $10 for the first collar (any variant), $5 for each additional collar.
    shipping: { first: 10.00, additional: 5.00 },
  },
  {
    id: "steering-wheel-hook",
    category: "race-car-parts",
    name: "Steering Wheel Hook with GoPro Mount",
    pageUrl: "https://www.frogracing.us/store/steering-wheel-hook",
    image: "images/steering-wheel-hook/38mm-standard-abs.jpg",
    description: "Lightweight 2-in-1 solution to hook a steering wheel to a rollcage bar, plus a standard GoPro mount.",
    variants: [
      { id: "38mm-standard-abs", label: "1.5\" / 38mm standard (ABS)", price: 12.00, image: "images/steering-wheel-hook/38mm-standard-abs.jpg" },
      { id: "38mm-hd-pa6cf", label: "1.5\" / 38mm HD (PA6-CF)", price: 17.00, image: "images/steering-wheel-hook/38mm-hd-pa6cf.jpg" },
      { id: "44mm-standard-abs", label: "1.75\" / 44mm standard (ABS)", price: 12.00, image: "images/steering-wheel-hook/44mm-standard-abs.jpg" },
      { id: "44mm-hd-pa6cf", label: "1.75\" / 44mm HD (PA6-CF)", price: 17.00, image: "images/steering-wheel-hook/44mm-hd-pa6cf.jpg" },
      { id: "44mm-xl-standard-abs", label: "1.75\" / 44mm XL standard (ABS)", price: 22.00, image: "images/steering-wheel-hook/44mm-xl-standard-abs.jpg" },
      { id: "44mm-xl-hd-pa6cf", label: "1.75\" / 44mm XL HD (PA6-CF)", price: 27.00, image: "images/steering-wheel-hook/44mm-xl-hd-pa6cf.jpg" },
      { id: "contour-38mm-hd", label: "HD Contour camera adapter + 1.5\" / 38mm hook (PA6-CF)", price: 25.00, image: "images/steering-wheel-hook/contour-38mm-hd.jpg" },
      { id: "contour-44mm-hd", label: "HD Contour camera adapter + 1.75\" / 44mm hook (PA6-CF)", price: 25.00, image: "images/steering-wheel-hook/contour-44mm-hd.jpg" },
      { id: "contour-44mm-xl-hd", label: "HD Contour camera adapter + 1.75\" / 44mm XL hook (PA6-CF)", price: 30.00, image: "images/steering-wheel-hook/contour-44mm-xl-hd.jpg" },
    ],
    shipping: { first: 6.00, additional: 1.00 },
  },
  {
    id: "sun-visor",
    category: "race-car-parts",
    name: "Sun Visor GoPro Mount",
    pageUrl: "https://www.frogracing.us/store/sun-visor",
    image: "images/sun-visor/standalone.jpg",
    description: "Black ABS plastic sun visor with a versatile GoPro mount.",
    variants: [
      { id: "standalone", label: "Standalone visor (one visor)", price: 25.00, image: "images/sun-visor/standalone.jpg" },
      { id: "combo-1.5", label: "1.5\" Combo - Visor+1.5\" bar mount+GoPro thumbscrew+Cable tie", price: 30.00, image: "images/sun-visor/combo-1.5.jpg" },
      { id: "combo-1.75", label: "1.75\" Combo - Visor+1.75\" bar mount+GoPro thumbscrew+Cable tie", price: 30.00, image: "images/sun-visor/combo-1.75.jpg" },
      { id: "deluxe-1.5", label: "1.5\" Deluxe - Visor+1.5\" bar mount+Swivel mount+Cable tie", price: 49.00, image: "images/sun-visor/deluxe-1.5.jpg" },
      { id: "deluxe-1.75", label: "1.75\" Deluxe - Visor+1.75\" bar mount+Swivel mount+Cable tie", price: 49.00, image: "images/sun-visor/deluxe-1.75.jpg" },
      { id: "custom", label: "Custom design (contact sales@frogracing.us)", price: 79.00, image: "images/sun-visor/custom.jpg" },
    ],
    shipping: { first: 9.00, additional: 1.00 },
  },
  {
    id: "button-cover-fire-suppression",
    category: "race-car-parts",
    name: "Button Cover for Lifeline Fire Suppression Systems",
    pageUrl: "https://www.frogracing.us/store/button-cover-for-lifeline-fire-suppression-systems",
    image: "images/button-cover-fire-suppression/red-bg-white-e.jpg",
    description: "Fits Lifeline Zero 360 FIA 3.0kg FK 5-1-12 Stored Pressure Electric System buttons.",
    variants: [
      { id: "red-bg-white-e", label: "Red background, white E (pair)", price: 5.00, image: "images/button-cover-fire-suppression/red-bg-white-e.jpg" },
      { id: "white-bg-red-e", label: "White background, red E (pair)", price: 5.00, image: "images/button-cover-fire-suppression/white-bg-red-e.jpg" },
    ],
    shipping: { first: 4.00, additional: 1.00 },
  },
  {
    id: "steering-wheel-plug",
    category: "race-car-parts",
    name: "Steering Wheel Horn Plug",
    pageUrl: "https://www.frogracing.us/store/steering-wheel-plug",
    image: "images/steering-wheel-plug/sti.jpg",
    description: "Fits the standard Sparco steering wheel horn button hole.",
    variants: [
      { id: "sti", label: "STi", price: 10.00, image: "images/steering-wheel-plug/sti.jpg" },
      { id: "audi-rings", label: "Audi rings", price: 10.00, image: "images/steering-wheel-plug/audi-rings.jpg" },
      { id: "vw-logo", label: "VW logo", price: 10.00, image: "images/steering-wheel-plug/vw-logo.jpg" },
      { id: "custom", label: "Custom design (contact sales@frogracing.us)", price: 20.00, image: "images/steering-wheel-plug/custom.jpg" },
      { id: "blank", label: "Blank (all black/carbon fiber finish)", price: 8.00, image: "images/steering-wheel-plug/blank.jpg" },
    ],
    shipping: { first: 5.00, additional: 1.00 },
  },
  {
    id: "cttc-road-cutout",
    category: "3d-art",
    name: "Climb to the Clouds Glow in the Dark",
    images: ["images/cttc-road-cutout/front.jpg", "images/cttc-road-cutout/ruler.jpg"],
    description: "A cutout of the Mt Washington Climb to the Clouds auto road made from our GPS data from racing. This is a smaller version of our bigger 3D art, just the road, printed in Glow in the Dark green PLA filament. A great little piece to put on your desk or your shelf, great add-on to any order! Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 2.00,
    shipping: { first: 5.00, additional: 0.00 },
  },
  {
    id: "wim-pikes-peak-plaque",
    category: "3d-art",
    pageUrl: "https://www.frogracing.us/store/3d-art/women-in-motorsports-hillclimb-art",
    name: "Pikes Peak Women in Motorsports Edition",
    images: ["images/wim-pikes-peak-plaque/front.jpg", "images/wim-pikes-peak-plaque/detail.jpg"],
    description: "A special edition 3D print of the Pikes Peak hillclimb race celebrating women in motorsports and the 40th anniversary of Michele Mouton's victory in the Audi S1 at Pikes Peak, alongside the Frog Racing all-women team running in 2026. The Start Line arch, Glen Cove house, and mountain summit are printed in Glow in the Dark filament. Includes a 2D cutout of the road through the plate (can be hung on a wall) and an embossed Frog Racing logo on the back. Designed and manufactured in the USA with PLA filament (avoid temperatures above 120F). Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 80.00,
    shipping: { first: 20.00, additional: 10.00 },
  },
  {
    id: "wim-hillclimb-plaque",
    category: "3d-art",
    pageUrl: "https://www.frogracing.us/store/3d-art/women-in-motorsports-hillclimb-art",
    name: "Frog Racing 2026 Women in Motorsports Hillclimb Art",
    image: "images/wim-hillclimb-plaque/front.jpg",
    description: "A 29x27x14cm (11.4x10.6x5.5\") piece featuring all the New England Hillclimb Association mountains (Ascutney, Burke, Okemo, and Philo), Mt Washington Climb to the Clouds, and the Pikes Peak International Hillclimb - the events Frog Racing is entering in 2026. Course length and summit altitudes are featured on the base plate, with all road traces made from the team's own GPS data collected while racing. The back shows a 2D cutout of the roads plus an embossed Frog Racing logo. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 80.00,
    shipping: { first: 20.00, additional: 10.00 },
  },
  {
    id: "cttc-limited-edition",
    category: "3d-art",
    pageUrl: "https://www.frogracing.us/store/3d-art/climb-to-the-clouds-3d-art",
    name: "Climb to the Clouds Limited Edition",
    images: ["images/cttc-limited-edition/front.jpg", "images/cttc-limited-edition/detail.jpg"],
    description: "A unique piece of art limited to 100 copies, each individually numbered from 1/100 to 100/100, created to raise funds for SCCNH to organize Mt Washington Climb to the Clouds 2026. The 3D road features mile markers embossed in the edge, Glow in the Dark start line, twin bridge, and summit mountain. The base plate features the Climb to the Clouds 2026 logo and the piece's unique number in Glow in the Dark green, plus the names of the main spectator points (Start, Signal Corps, Cragway, and Cow Pasture). The mountain pillar is embossed with Mt Washington and its altitude. Includes 2D cutouts of the road, with a CTTC Launch Limited Edition print embedded on the back. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 105.00,
    shipping: { first: 20.00, additional: 10.00 },
  },
  {
    id: "neha-cttc-plaque",
    category: "3d-art",
    pageUrl: "https://www.frogracing.us/store/3d-art/neha-hillclimb-art",
    name: "NEHA + Climb to the Clouds",
    image: "images/neha-cttc-plaque/front.jpg",
    description: "A 29x23cm (11.4x9.05\") piece featuring all the New England Hillclimb Association mountains (Ascutney, Burke, Okemo, and Philo) and Mt Washington Climb to the Clouds. Course length and summit altitudes are featured on the base plate, with the NEHA hillclimbs text in Glow in the Dark green and Mt Washington in white. All road traces are made from the team's own GPS data collected while racing. The back shows a 2D cutout of the roads plus an embossed Frog Racing logo. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 60.00,
    shipping: { first: 18.00, additional: 10.00 },
  },
  {
    id: "neha-hillclimbs-plaque",
    category: "3d-art",
    pageUrl: "https://www.frogracing.us/store/3d-art/neha-hillclimb-art",
    name: "NEHA Hillclimbs",
    image: "images/neha-hillclimbs-plaque/front.jpg",
    description: "A 16x18cm (6.3x7.1\") piece featuring all the New England Hillclimb Association mountains (Ascutney, Burke, Okemo, and Philo), with course length and summit altitudes featured on the base plate. The NEHA hillclimbs text is in Glow in the Dark green. All road traces are made from the team's own GPS data collected while racing. The back shows a 2D cutout of the roads plus an embossed Frog Racing logo. Currently only shipping to the USA; contact sales@frogracing.us for international shipping.",
    price: 40.00,
    shipping: { first: 14.00, additional: 5.00 },
  },
];

// Fallback graduated shipping for products that don't yet have a real rate
// (flat per unit until the user gives us actual numbers).
const DEFAULT_SHIPPING = { first: 6.00, additional: 6.00 };
