// "Recommended Products" section: affiliate picks grouped by category, each with
// a thumbnail and the Amazon price seen when the data was last refreshed.
// The data (RECOMMENDED, RECOMMENDED_CHECKED) comes from recommended-data.js,
// which is generated by tools/build-recommended.js.

// Web app URL of google-apps-script-prices.gs (see the setup steps at the top of that
// file). While this is blank, or if the request fails, the page shows the dated
// snapshot in recommended-data.js instead.
const RECOMMENDED_LIVE_URL = "";

// Set once live prices have been applied: the ISO time Amazon was last asked.
let recLiveAt = null;

const AMAZON_STOREFRONT = "https://www.amazon.com/shop/frogracing";
const TIRE_RACK_LINK = "https://www.tkqlhce.com/click-101708275-10377982";

function recEsc(text) {
  return String(text).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function recMoney(amount) {
  return "$" + amount.toFixed(2);
}

function recThumbUrl(imageId, size) {
  return `https://m.media-amazon.com/images/I/${imageId}._AC_UL${size}_.jpg`;
}

// Amazon prices change constantly, so how old the data is decides how it may be shown:
//   under 2 hours   shown as current
//   2 hours - 7 days shown with a "may be out of date" notice
//   over 7 days     prices, discounts and deal tags are hidden (thumbnails and links stay)
const REC_STALE_AFTER_MS = 2 * 60 * 60 * 1000;
const REC_HIDE_AFTER_MS = 7 * 24 * 60 * 60 * 1000;

// When the prices on screen were fetched: the live data's time, else the snapshot's.
function recDataAgeMs() {
  return Date.now() - new Date(recLiveAt || RECOMMENDED_CHECKED).getTime();
}

function recPricesExpired() {
  return recDataAgeMs() > REC_HIDE_AFTER_MS;
}

function recOnSale(item) {
  if (recPricesExpired()) return false;
  return !!(item.pct || item.coupon || item.deal);
}

function recIsProduct(item) {
  return item.note === undefined;
}

function recCheckedLabel() {
  const date = new Date(RECOMMENDED_CHECKED);
  return date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

function recFinePrint() {
  const checked = new Date(recLiveAt || RECOMMENDED_CHECKED);
  const when = checked.toLocaleString("en-US", { month: "long", day: "numeric", hour: "numeric", minute: "2-digit" });
  const applies = `The price shown on Amazon when you buy is the one that applies.`;

  if (recPricesExpired()) {
    return (
      `Current Amazon prices are temporarily unavailable here (last updated ${checked.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}), ` +
      `so each item links to its Amazon page for today's price and any discount. Thumbnails are from Amazon.com.`
    );
  }
  if (recLiveAt && recDataAgeMs() <= REC_STALE_AFTER_MS) {
    return `Prices, discounts and availability are from Amazon.com as of ${when} and refresh about once an hour. ${applies}`;
  }
  if (recLiveAt) {
    return `Prices were last updated from Amazon.com on ${when} and may be out of date. ${applies}`;
  }
  return (
    `Amazon prices and discounts were last checked on ${recCheckedLabel()} and change often, ` +
    `so they may be out of date. ${applies} Thumbnails and prices are from Amazon.com.`
  );
}

// Overlay the hourly Amazon data (see google-apps-script-prices.gs) onto the
// snapshot: { updatedAt, items: { ASIN: { p, l, d, b, i, u } } }.
function recApplyLive(data) {
  if (!data || !data.items || !data.updatedAt) return false;
  let applied = 0;
  for (const category of RECOMMENDED) {
    for (const sub of category.subsections) {
      for (const item of sub.items) {
        const live = item.asin && data.items[item.asin];
        if (!live) continue;
        item.price = live.p == null ? undefined : live.p;
        item.was = live.l || undefined;
        item.pct = live.d || undefined;
        item.deal = live.b || undefined;
        item.coupon = undefined; // coupons are not part of the API data
        item.unavailable = live.u ? true : undefined;
        if (live.i) item.img = live.i;
        applied++;
      }
    }
  }
  if (applied) recLiveAt = data.updatedAt;
  return applied > 0;
}

async function recLoadLive() {
  if (!RECOMMENDED_LIVE_URL) return;
  try {
    const response = await fetch(RECOMMENDED_LIVE_URL);
    if (!response.ok) return;
    if (recApplyLive(await response.json())) renderRecommended();
  } catch (e) {
    // Offline or endpoint down: keep the snapshot.
  }
}

function recPriceHtml(item) {
  if (item.vendor) {
    return `<span class="rec-vendor">View at ${recEsc(item.vendor)} &rarr;</span>`;
  }
  if (recPricesExpired()) {
    return `<span class="rec-unknown">See price on Amazon &rarr;</span>`;
  }
  if (item.unavailable) {
    return `<span class="rec-unknown">Currently unavailable</span>`;
  }
  if (item.price == null) {
    return `<span class="rec-unknown">See price on Amazon &rarr;</span>`;
  }
  let html = `<b class="rec-now">${recMoney(item.price)}</b>`;
  if (item.was) html += ` <s class="rec-was">${recMoney(item.was)}</s>`;
  if (item.pct) html += ` <span class="rec-pct">&minus;${item.pct}%</span>`;
  return html;
}

function recTagsHtml(item) {
  if (recPricesExpired()) return "";
  const tags = [];
  if (item.deal === "pbd") tags.push(`<span class="rec-tag rec-tag-deal">Prime Big Deal</span>`);
  else if (item.deal === "ltd") tags.push(`<span class="rec-tag rec-tag-deal">Limited-time deal</span>`);
  if (item.coupon) tags.push(`<span class="rec-tag">${recEsc(item.coupon)}</span>`);
  return tags.length ? `<span class="rec-tags">${tags.join("")}</span>` : "";
}

// A note such as "See the DIY videos on our Subaru maintenance page" links the words
// that were linked on the original page ("Subaru maintenance"). If those words can't be
// found in the note (the page just showed the bare URL), the whole note is the link.
function recNoteHtml(text, links) {
  let html = recEsc(text);
  const unplaced = [];
  for (const link of links) {
    const words = link.t ? recEsc(link.t) : "";
    const anchor = (inner) => `<a href="${recEsc(link.h)}">${inner}</a>`;
    if (words && html.includes(words) && !html.includes(">" + words + "<")) {
      html = html.replace(words, anchor(words));
    } else {
      unplaced.push(link);
    }
  }
  if (unplaced.length === 1 && html === recEsc(text)) {
    html = `<a href="${recEsc(unplaced[0].h)}">${html}</a>`;
  }
  return html;
}

function recBuildItem(item) {
  if (!recIsProduct(item)) {
    const note = document.createElement("p");
    note.className = "rec-note";
    note.innerHTML = recNoteHtml(item.note, item.links || []);
    return note;
  }

  const link = document.createElement("a");
  link.className = "rec-item";
  link.href = item.url;
  link.target = "_blank";
  link.rel = "noopener sponsored";

  const name = item.name || item.title || "Product";
  const thumb = item.img
    ? `<img loading="lazy" alt="" src="${recThumbUrl(item.img, 160)}" srcset="${recThumbUrl(item.img, 320)} 2x">`
    : `<span class="rec-thumb-empty">${recEsc((item.vendor || "Amazon").charAt(0))}</span>`;

  link.innerHTML =
    `<span class="rec-thumb">${thumb}</span>` +
    `<span class="rec-info">` +
    `<span class="rec-name">${recEsc(name)}</span>` +
    `<span class="rec-price">${recPriceHtml(item)}</span>` +
    recTagsHtml(item) +
    `</span>`;
  return link;
}

function recBuildCategory(category) {
  const details = document.createElement("details");
  details.className = "rec-cat";

  const products = category.subsections.flatMap((s) => s.items.filter(recIsProduct));
  const onSale = products.filter(recOnSale).length;

  const summary = document.createElement("summary");
  summary.innerHTML =
    `<span class="rec-cat-name">${recEsc(category.name)}</span>` +
    `<span class="rec-cat-count">${products.length} item${products.length === 1 ? "" : "s"}</span>` +
    (onSale ? `<span class="rec-cat-sale">${onSale} on sale</span>` : "");
  details.appendChild(summary);

  const body = document.createElement("div");
  body.className = "rec-cat-body";
  for (const sub of category.subsections) {
    const block = document.createElement("div");
    block.className = "rec-sub-block";

    if (sub.name || sub.link) {
      const heading = document.createElement("h4");
      heading.className = "rec-sub";
      heading.textContent = sub.name || "More";
      if (sub.link) {
        heading.insertAdjacentHTML(
          "beforeend",
          ` <a class="rec-see-all" href="${recEsc(sub.link)}" target="_blank" rel="noopener sponsored">See the full list on Amazon &rarr;</a>`
        );
      }
      block.appendChild(heading);
    }

    const grid = document.createElement("div");
    grid.className = "rec-grid";
    let lastGroup = null;
    for (const item of sub.items) {
      if (item.group && item.group !== lastGroup) {
        const groupHeading = document.createElement("h5");
        groupHeading.className = "rec-group";
        groupHeading.textContent = item.group;
        grid.appendChild(groupHeading);
      }
      lastGroup = item.group || null;
      const node = recBuildItem(item);
      node.dataset.search = (item.name || item.title || item.note || "").toLowerCase();
      if (recIsProduct(item)) node.dataset.sale = recOnSale(item) ? "1" : "";
      grid.appendChild(node);
    }
    block.appendChild(grid);
    body.appendChild(block);
  }
  details.appendChild(body);
  return details;
}

// Search / "on sale only" filter. Opens the categories that have matches and
// hides everything else.
function recApplyFilter(root) {
  const query = root.querySelector(".rec-search").value.trim().toLowerCase();
  const saleOnly = root.querySelector(".rec-sale-only").checked;
  const filtering = !!query || saleOnly;
  let totalShown = 0;

  for (const cat of root.querySelectorAll(".rec-cat")) {
    let shown = 0;
    for (const block of cat.querySelectorAll(".rec-sub-block")) {
      let blockShown = 0;
      let group = null;
      let groupShown = 0;
      // A group heading only stays visible if something under it does.
      const closeGroup = () => {
        if (group) group.hidden = filtering && groupShown === 0;
      };
      for (const node of block.querySelectorAll(".rec-grid > *")) {
        if (node.classList.contains("rec-group")) {
          closeGroup();
          group = node;
          groupShown = 0;
          continue;
        }
        const isProduct = node.classList.contains("rec-item");
        const matches =
          (!query || node.dataset.search.includes(query)) && (!saleOnly || (isProduct && node.dataset.sale === "1"));
        node.hidden = filtering && !matches;
        if (!node.hidden) {
          blockShown++;
          groupShown++;
        }
      }
      closeGroup();
      block.hidden = filtering && blockShown === 0;
      shown += blockShown;
    }
    cat.hidden = filtering && shown === 0;
    if (filtering && shown > 0) cat.open = true;
    totalShown += shown;
  }
  root.querySelector(".rec-empty").hidden = !(filtering && totalShown === 0);
}

function renderRecommended() {
  const root = document.getElementById("recommended");
  if (!root || typeof RECOMMENDED === "undefined" || RECOMMENDED.length === 0) return;

  // The page is redrawn when live prices arrive; keep what the shopper had open/typed.
  const previous = root.querySelector(".rec-list")
    ? {
        open: [...root.querySelectorAll(".rec-cat[open] .rec-cat-name")].map((el) => el.textContent),
        query: root.querySelector(".rec-search").value,
        saleOnly: root.querySelector(".rec-sale-only").checked,
      }
    : null;

  const productCount = RECOMMENDED.reduce(
    (n, c) => n + c.subsections.reduce((m, s) => m + s.items.filter(recIsProduct).length, 0),
    0
  );

  root.innerHTML =
    `<h2>Recommended Products</h2>` +
    `<p class="rec-intro">Gear we have reviewed, tested and actively use &mdash; ${productCount} picks across ` +
    `${RECOMMENDED.length} categories. As an Amazon Associate we earn from qualifying purchases made from these links ` +
    `(at no cost to you); the commissions directly fund our <a href="https://www.frogracing.us/wim">Women in Motorsports</a> efforts. ` +
    `Also see our <a href="${AMAZON_STOREFRONT}" target="_blank" rel="noopener sponsored">Amazon storefront</a> and our ` +
    `<a href="${TIRE_RACK_LINK}" target="_blank" rel="noopener sponsored">Tire Rack</a> affiliate link.</p>` +
    `<div class="rec-controls">` +
    `<input class="rec-search" type="search" placeholder="Search recommended products" aria-label="Search recommended products">` +
    `<label class="rec-sale-label"${recPricesExpired() ? " hidden" : ""}><input class="rec-sale-only" type="checkbox"> On sale only</label>` +
    `</div>` +
    `<div class="rec-list"></div>` +
    `<p class="rec-empty" hidden>No recommended products match.</p>` +
    `<p class="rec-fineprint">${recFinePrint()}</p>`;

  const list = root.querySelector(".rec-list");
  for (const category of RECOMMENDED) list.appendChild(recBuildCategory(category));

  const apply = () => recApplyFilter(root);
  root.querySelector(".rec-search").addEventListener("input", apply);
  root.querySelector(".rec-sale-only").addEventListener("change", apply);

  if (previous) {
    for (const cat of root.querySelectorAll(".rec-cat")) {
      cat.open = previous.open.includes(cat.querySelector(".rec-cat-name").textContent);
    }
    root.querySelector(".rec-search").value = previous.query;
    root.querySelector(".rec-sale-only").checked = previous.saleOnly;
    apply();
  }
}

// Same menu as the store page: every product category (linking back to its section
// there), then this page as the last entry.
function renderRecommendedNav() {
  const nav = document.getElementById("category-nav");
  nav.innerHTML = "";
  for (const category of CATEGORIES) {
    if (!PRODUCTS.some((p) => p.category === category.id)) continue;
    const link = document.createElement("a");
    link.href = `./#${category.id}`;
    link.textContent = category.label;
    nav.appendChild(link);
  }
  const current = document.createElement("a");
  current.href = "recommended.html";
  current.textContent = "Recommended Products";
  current.className = "current";
  current.setAttribute("aria-current", "page");
  nav.appendChild(current);
}

renderRecommendedNav();
renderRecommended();
recLoadLive();
